[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

[dependencies]
openzeppelin-contracts-upgradeable = { version = "v4.9.3" , git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable" }

[remappings]
"@openzeppelin/contracts/"="lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/"
"@openzeppelin/contracts-upgradeable/"="lib/openzeppelin-contracts-upgradeable/contracts/"

