[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "out" }]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
OPENZEPPELIN_BASH_PATH="D:/Git/bin/bash"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
